# **TUGAS NUMPY**

---

Nama: Dzaki Althalsyah

NIM: 245150407111071

Setelah mengikuti workshop Numpy dan Pandas, tentunya kalian sudah mulai memahami hal-hal apa saja yang akan dilakukan oleh Data Scientist dengan Numpy. Sekarang, saatnya mengukur kemampuan kalian dari apa yang telah kalian dapatkan pada workshop sebelumnya.

**Deadline: Jumat, 21 Februari 2025**


# **📊 Numpy Exercise 📊**

Selamat datang di latihan eksplorasi data menggunakan **Numpy**!  

---

## **📌 Soal 1: Regresi Linear** 📝

Saat offline/online assessment kemarin ada persoalaan **Regresi Linear**, nah coba kamu buat menggunakan python dan numpy termasuk poin-poin berikut: <br>
✅ Fungsi regresi mampu menerima array A dan array B dan memprediksi slope dan intercept<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X <br>

In [2]:
import numpy as np

In [3]:
A = np.array([10, 21, 31, 14, 5])
B = np.array([2, 27, 13, 9, 33])

mean_x = np.mean(A)
mean_y = np.mean(B)

numerator = np.sum((A - mean_x) * (B - mean_y))
denominator = np.sum((A - mean_x) ** 2)

slope = numerator / denominator
intercept = mean_y - (slope * mean_x)

nilai_baru = int(input("Masukkan nilai X: "))
nilai_prediksi = (slope * nilai_baru) + intercept

print("Slope:", slope)
print("Intercept:", intercept)
print("Prediksi untuk X =", nilai_baru ,":", nilai_prediksi)

Masukkan nilai X: 6
Slope: -0.19425511197663092
Intercept: 19.946932814021423
Prediksi untuk X = 6 : 18.78140214216164


## **📌 Soal 2: Regresi Polinomial** 📝

Saat offline/online assessment kemarin ada persoalan **Regresi Linear**, nah sekarang coba kamu buat **Regresi Polinomial** menggunakan Python dan NumPy, termasuk poin-poin berikut:<br>
✅ Fungsi regresi mampu menerima array A dan array B serta menyesuaikan data dengan polinomial derajat tertentu.<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X.<br>
✅ Hasil regresi mencetak koefisien polinomial yang dihasilkan.<br>

In [4]:
A = np.array([10, 21, 31, 14, 5])
B = np.array([2, 27, 13, 9, 33])

derajat = 2

X = np.array([A**i for i in range(derajat + 1)]).T

koefisien = np.linalg.lstsq(X, B, rcond=None)[0]

for i, coef in enumerate(koefisien):
    print(f"x^{i}: {coef}")

nilai_baru = 6
nilai_prediksi = sum(coef * (nilai_baru**i) for i, coef in enumerate(koefisien))

print("Prediksi untuk X =", nilai_baru, ":", nilai_prediksi)


x^0: 31.413523050412863
x^1: -1.888532143431988
x^2: 0.04637463050837276
Prediksi untuk X = 6 : 21.751816888122356


## **📌 Soal 3: Random Values Array** 📝

Pertama-tama, buatlah **Array Integer 10x10x10** dengan elemen **random** dan carikan:<br>
1️⃣ Cari elemen minimum dan maksimum dalam array tersebut?<br>
2️⃣ Carilah rata-rata dan median seluruh elemen dalam array tersebut?<br>

In [5]:
import numpy as np

arr_rand = np.random.randint(0, 10000000, size=(10, 10, 10))
arr_rand

array([[[8271146, 6489788, 2923564, 4492353, 9853728, 8221032, 6990169,
          270757, 4967906,  784809],
        [3835314, 2724904, 9302020, 4729971, 2608632,  119175, 8353833,
         4021163, 7982907, 7538025],
        [7322662, 1079341, 9038492, 9996796, 6508857, 2815992, 4159645,
         9915266, 6591921, 6894165],
        [3426051, 7450621, 2747329, 8121594, 7503761, 4618932,  827018,
         2830933, 4122859,  234222],
        [9234948, 7884865, 6876889, 4067330, 7438991, 8050490, 8915386,
         1925125, 3305941,  824628],
        [ 906995, 2844904, 7828694, 8127749,  456527, 2573750, 7658060,
         3130893, 8087415, 9253327],
        [ 190252,  772479, 9216415, 2512848,  318879, 3987703, 5031101,
          995620,  161527, 5553186],
        [8190712, 5279422,  277217, 6623806, 9964387, 9284874, 2275099,
          102182, 7570384, 1163314],
        [8681734, 6100816, 5845954, 3633023, 6779981, 2936201, 1282698,
         1459264, 8873904, 4875425],
        [8788428, 7

In [6]:
min = np.amin(arr_rand)
max = np.amax(arr_rand)
mean = np.mean(arr_rand)
median = np.median(arr_rand)

print(f"Nilai minimum: {min}")
print(f"Nilai maksimum: {max}")
print(f"Nilai rata-rata: {mean}")
print(f"Nilai median: {median}")

Nilai minimum: 21725
Nilai maksimum: 9996819
Nilai rata-rata: 5004009.419
Nilai median: 4964083.5


## **📌 Soal 4: 2D Array Shenanigans** 📝

Tugas kamu disini adalah membuat **Array 2D** sesuai ketentuan masing-masing soal: <br>
1️⃣ Buatlah **array 10x10** yang memiliki angka "5" sebagai bingkai di seluruh tepi luar dan bagian dalam (selain array) berisi "8"? <br>
2️⃣ Buatlah **array 2d 8x8** dengan pola seperti **checkboard/catur** (1 untuk kotak hitam, 0 untuk kotak putih)?<br>
3️⃣ Buatlah **array 2d 15x15** dengan aturan sebagai berikut:
- Jika suatu angka dapat dibagi 2, isi dengan 2.
- Jika suatu angka dapat dibagi 3, isi dengan 3.
- Jika suatu angka dapat dibagi 5, isi dengan 5.
- Jika suatu angka dapat dibagi oleh lebih dari satu kondisi (misal, 6 bisa dibagi 2 & 3), maka simpan gabungan angka tersebut (misal, 6 → "23", 15 → "35").
- Jika tidak memenuhi kondisi apa pun, isi dengan 0.

In [7]:
bingkai = np.full((10, 10), 8)

bingkai[0, :] = 5
bingkai[-1, :] = 5
bingkai[:, 0] = 5
bingkai[:, -1] = 5

bingkai

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [8]:
catur = np.zeros((8, 8), dtype=int)
catur[1::2, ::2] = 1
catur[::2, 1::2] = 1
print(catur)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
arr_2d = np.zeros((15, 15), dtype=object)

for i in range(15):
    for j in range(15):
        num = i * 15 + j + 1
        hasil = ""
        if num % 2 == 0:
            hasil += "2"
        if num % 3 == 0:
            hasil += "3"
        if num % 5 == 0:
            hasil += "5"
        if not hasil:
            hasil = "0"
        arr_2d[i, j] = hasil

print(arr_2d)


[['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0

## **📌 Soal 5: Time & Date** 📝

Kamu disini diminta untuk memanfaatkan fitur numpy untuk tanggal: <br>
1️⃣ Bagaimana dengan numpy, kamu bisa mendapatkan tanggal hari ini, kemarin dan esok hari?<br>
2️⃣ Tampilkan hari yang ada di bulan Mei tahun 2020?<br>

In [19]:
now = np.datetime64('today')
yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')

print(now)
print(yesterday)
print(tomorrow)

hari_mei = np.arange('2020-05-01', '2020-06-01', dtype='datetime64[D]')

print(hari_mei)

2025-02-21
2025-02-20
2025-02-22
['2020-05-01' '2020-05-02' '2020-05-03' '2020-05-04' '2020-05-05'
 '2020-05-06' '2020-05-07' '2020-05-08' '2020-05-09' '2020-05-10'
 '2020-05-11' '2020-05-12' '2020-05-13' '2020-05-14' '2020-05-15'
 '2020-05-16' '2020-05-17' '2020-05-18' '2020-05-19' '2020-05-20'
 '2020-05-21' '2020-05-22' '2020-05-23' '2020-05-24' '2020-05-25'
 '2020-05-26' '2020-05-27' '2020-05-28' '2020-05-29' '2020-05-30'
 '2020-05-31']


## **📌 Soal 6: Slicing** 📝

Jika diketahui array `A`, maka buatlah program untuk mendapatkan elemen dibawah ini:
```python
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])
```

1️⃣ Ambil elemen yang berada pada baris `ke-4` dan kolom `ke-2` dari array `A` <br>
2️⃣ Buat `array 2D` yang hanya berisi bilangan prima dari `A` <br>
3️⃣ Ambil elemen-elemen yang berada di tepi luar dari array `A` dan gabungkan menjadi `Satu array 1D`. <br>
4️⃣ Dapatkan subbarray berikut:
```python
[[20, 40, 60],
 [80, 100, 120],
 [140, 160, 180],
 [200, 220, 240],
 [260, 280, 300]]
```
5️⃣ Dapatkan subbarray berikut:
```python
 [[30, 40],
 [90, 100],
 [150, 160],
 [210, 220]]
```

In [11]:
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])

print(A[3,1])

200


In [12]:
angka_prima = []
for i in A:
    for j in i:
        cek_prima = True
        if j <= 1:
            cek_prima = False
        else:
            for k in range(2, int(num**0.5) + 1):
                if num % k == 0:
                    cek_prima = False
                    break
        if cek_prima:
            angka_prima.append(j)

prima_2d = np.array(angka_prima).reshape(-1, 1)
print(prima_2d)

[]


In [13]:
tepi_luar = np.concatenate((A[0, :], A[-1, :], A[1:-1, 0], A[1:-1, -1]))
tepi_luar

array([ 10,  20,  30,  40,  50,  60, 250, 260, 270, 280, 290, 300,  70,
       130, 190, 120, 180, 240])

In [14]:
A[::1, 1::2]

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180],
       [200, 220, 240],
       [260, 280, 300]])

In [15]:
A[:4:1, 2:4:1]

array([[ 30,  40],
       [ 90, 100],
       [150, 160],
       [210, 220]])

## **📌 Soal 7: Ekspansi Array** 📝

Jika kamu memiliki array ***Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]***, buatlah kode untuk membuat array R berupa: <br>
***R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]***?

In [16]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])
print("R=", R)

R= [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
