# **TUGAS NUMPY**

---

Nama: Dzaki Althalsyah

NIM: 245150407111071

Setelah mengikuti workshop Numpy dan Pandas, tentunya kalian sudah mulai memahami hal-hal apa saja yang akan dilakukan oleh Data Scientist dengan Numpy. Sekarang, saatnya mengukur kemampuan kalian dari apa yang telah kalian dapatkan pada workshop sebelumnya.

**Deadline: Jumat, 21 Februari 2025**


# **📊 Numpy Exercise 📊**

Selamat datang di latihan eksplorasi data menggunakan **Numpy**!  

---

## **📌 Soal 1: Regresi Linear** 📝

Saat offline/online assessment kemarin ada persoalaan **Regresi Linear**, nah coba kamu buat menggunakan python dan numpy termasuk poin-poin berikut: <br>
✅ Fungsi regresi mampu menerima array A dan array B dan memprediksi slope dan intercept<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X <br>

In [17]:
import numpy as np

In [53]:
A = np.array([10, 21, 31, 14, 5])
B = np.array([2, 27, 13, 9, 33])

mean_x = np.mean(A)
mean_y = np.mean(B)

numerator = np.sum((A - mean_x) * (B - mean_y))
denominator = np.sum((A - mean_x) ** 2)

slope = numerator / denominator
intercept = mean_y - (slope * mean_x)

nilai_baru = int(input("Masukkan nilai X: "))
nilai_prediksi = (slope * nilai_baru) + intercept

print("Slope:", slope)
print("Intercept:", intercept)
print("Prediksi untuk X =", nilai_baru ,":", nilai_prediksi)

Masukkan nilai X: 6
Slope: -0.19425511197663092
Intercept: 19.946932814021423
Prediksi untuk X = 6 : 18.78140214216164


## **📌 Soal 2: Regresi Polinomial** 📝

Saat offline/online assessment kemarin ada persoalan **Regresi Linear**, nah sekarang coba kamu buat **Regresi Polinomial** menggunakan Python dan NumPy, termasuk poin-poin berikut:<br>
✅ Fungsi regresi mampu menerima array A dan array B serta menyesuaikan data dengan polinomial derajat tertentu.<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X.<br>
✅ Hasil regresi mencetak koefisien polinomial yang dihasilkan.<br>

In [57]:
A = np.array([10, 21, 31, 14, 5])
B = np.array([2, 27, 13, 9, 33])

derajat = 2

X = np.array([A**i for i in range(derajat + 1)]).T

koefisien = np.linalg.lstsq(X, B, rcond=None)[0]

for i, coef in enumerate(koefisien):
    print(f"x^{i}: {coef}")

nilai_baru = 6
nilai_prediksi = sum(coef * (nilai_baru**i) for i, coef in enumerate(koefisien))

print("Prediksi untuk X =", nilai_baru, ":", nilai_prediksi)


Koefisien Polinomial:
x^0: 31.413523050412863
x^1: -1.888532143431988
x^2: 0.04637463050837276
Prediksi untuk X = 6 : 21.751816888122356


## **📌 Soal 3: Random Values Array** 📝

Pertama-tama, buatlah **Array Integer 10x10x10** dengan elemen **random** dan carikan:<br>
1️⃣ Cari elemen minimum dan maksimum dalam array tersebut?<br>
2️⃣ Carilah rata-rata dan median seluruh elemen dalam array tersebut?<br>

In [19]:
import numpy as np

arr_rand = np.random.randint(0, 10000000, size=(10, 10, 10))
arr_rand

array([[[4267065, 7635072, 9808612,  975786, 9590139, 4440169, 2736315,
         2104305, 8927754, 9630680],
        [8239030, 7782189, 5546439, 9628292, 3546899, 4265437, 7531677,
         6998046, 4062963, 3974241],
        [1173832, 3084029, 7741063, 6856762, 6342531, 5052778, 2139337,
         6307311, 8779756, 8394058],
        [8492126, 5112629, 2442310, 1979432, 7796519, 1881353, 7348979,
         4340031, 7867959, 5354059],
        [3718466, 7615186,  604005, 1905033, 4689709, 7540446, 6111705,
         1394017,  135363, 3868254],
        [4306434, 3521677, 1727526, 2812468, 9544607, 3066217, 4307128,
         7774302, 7288757, 2128115],
        [2910836, 4495034, 9807090, 6473347, 1070074, 6386068, 6080067,
         3358860, 5927288, 9278802],
        [  21142, 1251766, 2206049, 2657570, 5725638, 7715038, 6056384,
         7808040,  251419, 5127622],
        [8530475, 6248398, 2932204, 3019889, 1780203,  262609, 8577543,
         3528305, 1196292, 4186004],
        [1600564, 9

In [20]:
min = np.amin(arr_rand)
max = np.amax(arr_rand)
mean = np.mean(arr_rand)
median = np.median(arr_rand)

print(f"Nilai minimum: {min}")
print(f"Nilai maksimum: {max}")
print(f"Nilai rata-rata: {mean}")
print(f"Nilai median: {median}")

Nilai minimum: 14635
Nilai maksimum: 9977081
Nilai rata-rata: 4992042.914
Nilai median: 4908357.5


## **📌 Soal 4: 2D Array Shenanigans** 📝

Tugas kamu disini adalah membuat **Array 2D** sesuai ketentuan masing-masing soal: <br>
1️⃣ Buatlah **array 10x10** yang memiliki angka "5" sebagai bingkai di seluruh tepi luar dan bagian dalam (selain array) berisi "8"? <br>
2️⃣ Buatlah **array 2d 8x8** dengan pola seperti **checkboard/catur** (1 untuk kotak hitam, 0 untuk kotak putih)?<br>
3️⃣ Buatlah **array 2d 15x15** dengan aturan sebagai berikut:
- Jika suatu angka dapat dibagi 2, isi dengan 2.
- Jika suatu angka dapat dibagi 3, isi dengan 3.
- Jika suatu angka dapat dibagi 5, isi dengan 5.
- Jika suatu angka dapat dibagi oleh lebih dari satu kondisi (misal, 6 bisa dibagi 2 & 3), maka simpan gabungan angka tersebut (misal, 6 → "23", 15 → "35").
- Jika tidak memenuhi kondisi apa pun, isi dengan 0.

In [21]:
bingkai = np.full((10, 10), 8)

bingkai[0, :] = 5
bingkai[-1, :] = 5
bingkai[:, 0] = 5
bingkai[:, -1] = 5

bingkai

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 8, 8, 8, 8, 8, 8, 8, 8, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [22]:
catur = np.zeros((8, 8), dtype=int)
catur[1::2, ::2] = 1
catur[::2, 1::2] = 1
print(catur)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
arr_2d = np.zeros((15, 15), dtype=object)

for i in range(15):
    for j in range(15):
        num = i * 15 + j + 1
        hasil = ""
        if num % 2 == 0:
            hasil += "2"
        if num % 3 == 0:
            hasil += "3"
        if num % 5 == 0:
            hasil += "5"
        if not hasil:
            hasil = "0"
        arr_2d[i, j] = hasil

print(arr_2d)


[['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0' '2' '35']
 ['2' '0' '23' '0' '25' '3' '2' '0' '23' '5' '2' '3' '2' '0' '235']
 ['0' '2' '3' '2' '5' '23' '0' '2' '3' '25' '0' '23' '0

## **📌 Soal 5: Time & Date** 📝

Kamu disini diminta untuk memanfaatkan fitur numpy untuk tanggal: <br>
1️⃣ Bagaimana dengan numpy, kamu bisa mendapatkan tanggal hari ini, kemarin dan esok hari?<br>
2️⃣ Tampilkan hari yang ada di bulan Mei tahun 2020?<br>

In [24]:
now = np.datetime64('today')
yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')

print(now)
print(yesterday)
print(tomorrow)

2025-02-20
2025-02-19
2025-02-21


## **📌 Soal 6: Slicing** 📝

Jika diketahui array `A`, maka buatlah program untuk mendapatkan elemen dibawah ini:
```python
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])
```

1️⃣ Ambil elemen yang berada pada baris `ke-4` dan kolom `ke-2` dari array `A` <br>
2️⃣ Buat `array 2D` yang hanya berisi bilangan prima dari `A` <br>
3️⃣ Ambil elemen-elemen yang berada di tepi luar dari array `A` dan gabungkan menjadi `Satu array 1D`. <br>
4️⃣ Dapatkan subbarray berikut:
```python
[[20, 40, 60],
 [80, 100, 120],
 [140, 160, 180],
 [200, 220, 240],
 [260, 280, 300]]
```
5️⃣ Dapatkan subbarray berikut:
```python
 [[30, 40],
 [90, 100],
 [150, 160],
 [210, 220]]
```

In [25]:
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])

print(A[3,1])

200


In [34]:
angka_prima = []
for i in A:
    for j in i:
        cek_prima = True
        if j <= 1:
            cek_prima = False
        else:
            for k in range(2, int(num**0.5) + 1):
                if num % k == 0:
                    cek_prima = False
                    break
        if cek_prima:
            angka_prima.append(j)

prima_2d = np.array(angka_prima).reshape(-1, 1)
print(prima_2d)

[]


In [27]:
tepi_luar = np.concatenate((A[0, :], A[-1, :], A[1:-1, 0], A[1:-1, -1]))
tepi_luar

array([ 10,  20,  30,  40,  50,  60, 250, 260, 270, 280, 290, 300,  70,
       130, 190, 120, 180, 240])

In [28]:
A[::1, 1::2]

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180],
       [200, 220, 240],
       [260, 280, 300]])

In [29]:
A[:4:1, 2:4:1]

array([[ 30,  40],
       [ 90, 100],
       [150, 160],
       [210, 220]])

## **📌 Soal 7: Ekspansi Array** 📝

Jika kamu memiliki array ***Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]***, buatlah kode untuk membuat array R berupa: <br>
***R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]***?

In [30]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])
print("R=", R)

R= [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
